FROM node:20-slim
WORKDIR /app

COPY package*.json ./
RUN npm ci             # instala deps en capa separada

COPY . .
EXPOSE 4200
ENV CHOKIDAR_USEPOLLING=true
CMD ["npm", "start"]
# equivalente a: ng serve --host 0.0.0.0 --poll=1000
