version: "3.9"
services:
  hubcon:
    build: ./hubcon
    ports:
      - "5000:5000"

  backend:
    build: ./backend
    environment:
      - HUB_URL=http://hubcon:5000/hub/images
    ports:
      - "8080:8080"
    depends_on:
      - hubcon

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
      - hubcon
